# Generated by Django 5.2.6 on 2025-09-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Media/Profile_Pics'),
        ),
    ]
