# Generated by Django 5.2.6 on 2025-09-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_customusermodel_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemodel',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
